<a href="https://colab.research.google.com/github/Marj-sunshine/Artificial-Intelligence-in-Internet-of-Things-Laboratories/blob/main/LAB5_BCA190(30_10_2025).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##LAB 5
Predict if a person has diabetes using Perceptron and MLP.

## 1: Perceptron

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes (1).csv to diabetes (1).csv

In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv('diabetes (1).csv')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
from sklearn import preprocessing

#Creating labelEncoder
le = preprocessing.LabelEncoder()

#Converting string to numbers
data['Species'] = le.fit_transform(data['Outcome'])

In [ ]:
x = data.iloc[:, [1,2,3,4]].values
y = data.iloc[:,8].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv('diabetes (1).csv')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
from collections.abc import ValuesView
x=data.iloc[:,[1,2,3,4]].values
y=data.iloc[:,8].values

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)

StandardScaler()

In [ ]:
#Apply the scaler to the training data
x_train_std = sc.transform(x_train)

#Apply the same transformation to the test data
x_test_std = sc.transform(x_test)

In [ ]:
from sklearn.linear_model import Perceptron
ppn = Perceptron(eta0=0.1, random_state=0)
ppn.fit(x_train_std, y_train)

Perceptron(eta0=0.1)

In [ ]:
y_pred = ppn.predict(x_test_std)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
y_test

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy:%.2f' % accuracy_score(y_test, y_pred))

Accuracy:0.67

##2 : Multi-layer Feed-forward network

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes (1).csv to diabetes (1) (2).csv

In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv('diabetes (1).csv')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
from sklearn import preprocessing

#Creating labelEncoder
le = preprocessing.LabelEncoder()

#Converting string to numbers
data['Species'] = le.fit_transform(data['Outcome'])

In [ ]:
#Splitting the data into features
x = data[['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']]
y = data['Outcome']  # CORRECT column name

#Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
#Import MLP Classifier
from sklearn.neural_network import MLPClassifier

#Create an object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

#Fit data onto the object
clf.fit(x_train,y_train)

Iteration 1, loss = 5.02990458
Iteration 2, loss = 2.09602088
Iteration 3, loss = 0.90401050
Iteration 4, loss = 0.71759264
Iteration 5, loss = 0.73472908
Iteration 6, loss = 0.70510296
Iteration 7, loss = 0.67092485
Iteration 8, loss = 0.68152621
Iteration 9, loss = 0.67657359
Iteration 10, loss = 0.66446076
Iteration 11, loss = 0.66705933
Iteration 12, loss = 0.66555409
Iteration 13, loss = 0.66114046
Iteration 14, loss = 0.66292238
Iteration 15, loss = 0.66103088
Iteration 16, loss = 0.65783714
Iteration 17, loss = 0.65897458
Iteration 18, loss = 0.65780284
Iteration 19, loss = 0.65585145
Iteration 20, loss = 0.65555549
Iteration 21, loss = 0.65531549
Iteration 22, loss = 0.65412856
Iteration 23, loss = 0.65404845
Iteration 24, loss = 0.65247674
Iteration 25, loss = 0.65142270
Iteration 26, loss = 0.65086830
Iteration 27, loss = 0.65038101
Iteration 28, loss = 0.64952099
Iteration 29, loss = 0.64836801
Iteration 30, loss = 0.64789994
Iteration 31, loss = 0.64777584
Iteration 32, loss = 0.64657913
Iteration 33, loss = 0.64568954
Iteration 34, loss = 0.64450326
Iteration 35, loss = 0.64351242
Iteration 36, loss = 0.64332770
Iteration 37, loss = 0.64274458
Iteration 38, loss = 0.64051812
Iteration 39, loss = 0.64074393
Iteration 40, loss = 0.64057544
Iteration 41, loss = 0.63744286
Iteration 42, loss = 0.63900733
Iteration 43, loss = 0.63727717
Iteration 44, loss = 0.63516351
Iteration 45, loss = 0.63634029
Iteration 46, loss = 0.63352521
Iteration 47, loss = 0.63312649
Iteration 48, loss = 0.63224138
Iteration 49, loss = 0.63076267
Iteration 50, loss = 0.62925466
Iteration 51, loss = 0.62951791
Iteration 52, loss = 0.62732792
Iteration 53, loss = 0.62730180
Iteration 54, loss = 0.62691937
Iteration 55, loss = 0.62477783
Iteration 56, loss = 0.62426656
Iteration 57, loss = 0.62486119
Iteration 58, loss = 0.62244189
Iteration 59, loss = 0.62354159
Iteration 60, loss = 0.62012366
Iteration 61, loss = 0.62221184
Iteration 62, loss = 0.61769543
Iteration 63, loss = 0.61814639
Iteration 64, loss = 0.61611650
Iteration 65, loss = 0.61650492
Iteration 66, loss = 0.61465048
Iteration 67, loss = 0.61445413
Iteration 68, loss = 0.61348535
Iteration 69, loss = 0.61132159
Iteration 70, loss = 0.61051781
Iteration 71, loss = 0.61023696
Iteration 72, loss = 0.60868251
Iteration 73, loss = 0.60818078
Iteration 74, loss = 0.60765246
Iteration 75, loss = 0.60882966
Iteration 76, loss = 0.60810339
Iteration 77, loss = 0.61170510
Iteration 78, loss = 0.60707790
Iteration 79, loss = 0.60378402
Iteration 80, loss = 0.60284573
Iteration 81, loss = 0.60169454
Iteration 82, loss = 0.60141388
Iteration 83, loss = 0.59938416
Iteration 84, loss = 0.59933272
Iteration 85, loss = 0.59625063
Iteration 86, loss = 0.60014915
Iteration 87, loss = 0.59542801
Iteration 88, loss = 0.59811054
Iteration 89, loss = 0.59333302
Iteration 90, loss = 0.59574880
Iteration 91, loss = 0.59322418
Iteration 92, loss = 0.59106374
Iteration 93, loss = 0.59107272
Iteration 94, loss = 0.58982737
Iteration 95, loss = 0.58914770
Iteration 96, loss = 0.58772595
Iteration 97, loss = 0.58700758
Iteration 98, loss = 0.58718613
Iteration 99, loss = 0.58417547
Iteration 100, loss = 0.58505526
Iteration 101, loss = 0.58397454
Iteration 102, loss = 0.58236135
Iteration 103, loss = 0.58115812
Iteration 104, loss = 0.58037864
Iteration 105, loss = 0.57982197
Iteration 106, loss = 0.58004545
Iteration 107, loss = 0.57685110
Iteration 108, loss = 0.57632875
Iteration 109, loss = 0.57596665
Iteration 110, loss = 0.57400140
Iteration 111, loss = 0.57403349
Iteration 112, loss = 0.57203115
Iteration 113, loss = 0.57263115
Iteration 114, loss = 0.57055607
Iteration 115, loss = 0.56920715
Iteration 116, loss = 0.56789495
Iteration 117, loss = 0.56686351
Iteration 118, loss = 0.56641396
Iteration 119, loss = 0.56421980
Iteration 120, loss = 0.56357358
Iteration 121, loss = 0.56230642
Iteration 122, loss = 0.56198767
Iteration 123, loss = 0.56103784
Iteration 124, loss = 0.56031990
Iteration 125, loss = 0.55887529
Iteration 126, loss = 0.55909838
Iteration 127, loss = 0.55921837
Iteration 128, loss = 0.55784092
Iteration 129, loss = 0.55721376
Iteration 130, loss = 0.55640571
Iteration 131, loss = 0.55555979
Iteration 132, loss = 0.55448429
Iteration 133, loss = 0.55433102
Iteration 134, loss = 0.55484173
Iteration 135, loss = 0.55241890
Iteration 136, loss = 0.55357210
Iteration 137, loss = 0.55308818
Iteration 138, loss = 0.55027587
Iteration 139, loss = 0.55005298
Iteration 140, loss = 0.54931172
Iteration 141, loss = 0.54935367
Iteration 142, loss = 0.54793998
Iteration 143, loss = 0.54866763
Iteration 144, loss = 0.54731576
Iteration 145, loss = 0.54638791
Iteration 146, loss = 0.54497135
Iteration 147, loss = 0.54540513
Iteration 148, loss = 0.54501045
Iteration 149, loss = 0.54593292
Iteration 150, loss = 0.54253683
Iteration 151, loss = 0.54249913
Iteration 152, loss = 0.54228635
Iteration 153, loss = 0.54126811
Iteration 154, loss = 0.54059903
Iteration 155, loss = 0.54020650
Iteration 156, loss = 0.54213722
Iteration 157, loss = 0.54123047
Iteration 158, loss = 0.54044964
Iteration 159, loss = 0.53864313
Iteration 160, loss = 0.53789291
Iteration 161, loss = 0.53874360
Iteration 162, loss = 0.53972823
Iteration 163, loss = 0.53729727
Iteration 164, loss = 0.53601528
Iteration 165, loss = 0.53469977
Iteration 166, loss = 0.53585211
Iteration 167, loss = 0.53545860
Iteration 168, loss = 0.53375410
Iteration 169, loss = 0.53287003
Iteration 170, loss = 0.53345204
Iteration 171, loss = 0.53331451
Iteration 172, loss = 0.53160221
Iteration 173, loss = 0.53305562
Iteration 174, loss = 0.53387262
Iteration 175, loss = 0.53377874
Iteration 176, loss = 0.53055538
Iteration 177, loss = 0.52981521
Iteration 178, loss = 0.52947018
Iteration 179, loss = 0.52819521
Iteration 180, loss = 0.52870332
Iteration 181, loss = 0.52771363
Iteration 182, loss = 0.52852885
Iteration 183, loss = 0.52908453
Iteration 184, loss = 0.52461765
Iteration 185, loss = 0.52728359
Iteration 186, loss = 0.52481375
Iteration 187, loss = 0.52750154
Iteration 188, loss = 0.52504269
Iteration 189, loss = 0.52384249
Iteration 190, loss = 0.52512769
Iteration 191, loss = 0.52344414
Iteration 192, loss = 0.52390088
Iteration 193, loss = 0.52181990
Iteration 194, loss = 0.52068941
Iteration 195, loss = 0.52013865
Iteration 196, loss = 0.51848034
Iteration 197, loss = 0.51896738
Iteration 198, loss = 0.51668182
Iteration 199, loss = 0.51785367
Iteration 200, loss = 0.51762220

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [ ]:
ypred=clf.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,ypred)

0.7792207792207793